sudo: required

env:
  - IMAGE_NAME=$TRAVIS_BUILD_DIR-$TRAVIS_BUILD_NUMBER

services:
  - docker

before_install:
  - docker build -t $IMAGE_NAME -f Dockerfile.dev .

script:
  - docker run $IMAGE_NAME npm run test -- --coverage
