sudo: required

services:
  - docker

before_install:
  - docker build -t matiascecchetto/fe-startup --build-arg nginx_amplify_key=$NGINX_AMPLIFY_KEY -f Dockerfile.dev .

script:
  - docker run matiascecchetto/fe-startup npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "fe-startup"
  env: "festartup-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-805374242281"
  bucket_path: "fe-startup"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
