sudo: required

services:
  - docker

before_install:
  - docker build -t $TRAVIS_BUILD_DIR-$TRAVIS_BUILD_NUMBER -f Dockerfile.dev .

script:
  - docker run $TRAVIS_BUILD_DIR-$TRAVIS_BUILD_NUMBER npm run test -- --coverage
