sudo: required

services:
  - docker

before_install:
  - docker build -t matiascecchetto/fe-startup -f Dockerfile.dev .

script:
  - docker run matiascecchetto/fe-startup npm run test -- --coverage
  - tra
